[package]
name = "belvm_gc"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
libc.workspace = true
thiserror.workspace = true
