[package]
name = "belalang_interactive_debug"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
belalang_compiler.workspace = true
belalang_vm.workspace = true
thiserror.workspace = true
