[package]
name = "belalang_vm"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"
authors = ["Vito Secona <secona00@gmail.com>"]

[dependencies]
belalang_macros.workspace = true
thiserror.workspace = true
