[package]
name = "belalang_vm"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
belalang_macros.workspace = true
thiserror.workspace = true
