# keep-sorted start
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 120
normalize_comments = true
wrap_comments = true
# keep-sorted end
