[package]
name = "belc"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
belvm.workspace = true
thiserror.workspace = true
unicode-ident = "1.0.18"
