[package]
name = "belalang_vm"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
belalang_core = { path = "../belalang_core" }
indexmap = "2.2.6"
thiserror = "1.0.61"
