[package]
name = "beltools_debug"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
belc.workspace = true
belvm.workspace = true
thiserror.workspace = true
