[package]
name = "belalang_compiler"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
belalang_vm.workspace = true
thiserror.workspace = true
unicode-ident = "1.0.18"
