[package]
name = "beltools_tests"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
belvm.workspace = true
belvm_bytecode.workspace = true
