[package]
name = "belalang"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
belalang_compiler.workspace = true
belalang_vm.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
