[package]
name = "belalang"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Vito Secona <secona00@gmail.com>"]

[dependencies]
belalang_compiler.workspace = true
belalang_vm.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
