[package]
name = "belalang"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
belalang_compiler.workspace = true
belalang_vm.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
