[package]
name = "belalang"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
belc.workspace = true
belvm.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
