#include "belalang/BIR/IR/BIR.h"

#include "TableGenBackends.h"
#include "Utils.h"
#include "mlir/TableGen/Operator.h"
#include "llvm/TableGen/TableGenBackend.h"

namespace belalang::bir {

void emitRustBindingDecls(const llvm::RecordKeeper &rk, llvm::raw_ostream &os) {
  os << "// Autogenerated by bir-tblgen; don't manually edit\n";
  os << "#[cxx::bridge(namespace = \"belalang::birgen2\")]\n";
  os << "pub mod ffi {\n";

  os.indent(4) << "unsafe extern \"C++\" {\n";

  os.indent(8) << "include!(\"BIRGen2.h\");\n";
  os.indent(8) << "type BIRGen2;\n";

  os.indent(8) << "fn create_birgen2(gen_ptr: usize) -> UniquePtr<BIRGen2>;\n";

  for (const auto *opRec : rk.getAllDerivedDefinitions("BIR_Op")) {
    mlir::tblgen::Operator op(opRec);
    OpMetadata M(op);

    // TODO: support more
    if (!(op.getNumResults() == 0 && op.getNumOperands() == 0 &&
          op.getNumAttributes() == 0))
      continue;

    if (M.requiresGuard()) {
      os.indent(8) << "type " + M.getGuardName() + ";\n";
      for (auto r : M.getRegionNames()) {
        os.indent(8) << "fn enter_" << r
                     << "(self: Pin<&mut " + M.getGuardName() + ">);\n";
      }
    }

    llvm::StringRef name = op.getCppClassName();

    os.indent(8) << "fn build" + name << "(self: Pin<&mut BIRGen2>)";
    if (M.requiresGuard())
      os << " -> UniquePtr<" + M.getGuardName() + ">";
    os << ";\n";
  }

  os.indent(4) << "}\n";

  os << "}\n";
}

} // namespace belalang::bir
