#include "belalang/BIR/IR/BIR.h"

#include "TableGenBackends.h"
#include "Utils.h"
#include "mlir/TableGen/Operator.h"
#include "llvm/TableGen/TableGenBackend.h"

void emitGuardClassesDecls(OpMetadata M, llvm::raw_ostream &os) {
  os.indent(8) << "type " + M.getGuardName() + ";\n";
  for (auto r : M.getRegionNames()) {
    os.indent(8) << "fn enter_" << r
                 << "(self: Pin<&mut " + M.getGuardName() + ">);\n";
  }
}

void emitBuilderFunction(OpMetadata M, llvm::raw_ostream &os) {
  os.indent(8) << "fn " + M.getBuilderName() << "(self: Pin<&mut BIRGen2>)";
  if (M.requiresGuard())
    os << " -> UniquePtr<" + M.getGuardName() + ">";
  os << ";\n";
}

namespace belalang::bir {

void emitRustBindingDecls(const llvm::RecordKeeper &rk, llvm::raw_ostream &os) {
  os << "// Autogenerated by bir-tblgen; don't manually edit\n";
  os << "#[cxx::bridge(namespace = \"belalang::bir::codegen\")]\n";
  os << "pub mod ffi {\n";

  os.indent(4) << "unsafe extern \"C++\" {\n";

  os.indent(8) << "include!(\"belalang/BIR/CodeGen/BIRGen.h\");\n";
  os.indent(8) << "type BIRGen2;\n";

  os.indent(8) << "fn create_birgen2(gen_ptr: usize) -> UniquePtr<BIRGen2>;\n";

  for (const auto *opRec : rk.getAllDerivedDefinitions("BIR_Op")) {
    mlir::tblgen::Operator op(opRec);
    OpMetadata M(op);

    if (!opRec->getValueAsBit("hasBIRGenBindings"))
      continue;

    os << "\n";
    os.indent(8) << "// " + M.getOpIdent() + "\n";
    if (M.requiresGuard())
      emitGuardClassesDecls(M, os);
    emitBuilderFunction(M, os);
  }

  os.indent(4) << "}\n";

  os << "}\n";
}

} // namespace belalang::bir
