load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@rules_rust//rust:defs.bzl", "rust_static_library")

package(default_visibility = ["//visibility:public"])

# ------------------------------------------------------------------------------
# Lexer
# ------------------------------------------------------------------------------

cc_library(
	name = "Lexer",
	srcs = glob(["Lexer/*.cpp"]),
	deps = [
		"//include:Lexer",
		"//include:Diag",
	],
)

# ------------------------------------------------------------------------------
# AST
# ------------------------------------------------------------------------------

cc_library(
    name = "AST",
    srcs = glob(["AST/*.cpp"]),
    deps = [
        "//include:Lexer",
        "//include:AST",
        "//include:Diag",
    ],
)

# ------------------------------------------------------------------------------
# BIR
# ------------------------------------------------------------------------------

cc_library(
    name = "BIR",
    srcs = glob(
        ["BIR/**/*.cpp"],
        exclude = ["BIR/**/*Test.cpp"],
    ),
    deps = [
        "//include:BIR",
        "@llvm-project//mlir:Pass",
        "@llvm-project//mlir:Analysis",
        "@llvm-project//mlir:Support",
        "@llvm-project//mlir:FunctionInterfaces",
        "@llvm-project//mlir:ControlFlowDialect",
        "@llvm-project//mlir:LLVMDialect",
        "@llvm-project//mlir:ControlFlowToLLVM",
        "@llvm-project//mlir:TransformUtils",
        "@llvm-project//mlir:Transforms",
    ],
)

[
    cc_test(
        name = test[:-4].replace("/", "_"),
        srcs = [test],
        deps = [
            ":BIR",
            "//include:BIR",
            "@googletest//:gtest_main",
        ],
    )
    for test in glob(["BIR/**/*Test.cpp"])
]

# ------------------------------------------------------------------------------
# BIRGen
# ------------------------------------------------------------------------------

cc_library(
    name = "BIRGen",
    srcs = [
        "BIRGen/BIRGen.cpp",
        "BIRGen/TypeChecker.cpp",
    ],
    deps = [
        "//include:AST",
        "//include:BIR",
        "//include:BIRGen",
        "//include:Diag",
        "//include:Lexer",
        "//lib:BIR",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:Pass",
        "@llvm-project//mlir:Support",
    ],
)

# ------------------------------------------------------------------------------
# LLVMGen
# ------------------------------------------------------------------------------

cc_library(
    name = "LLVMGen",
    srcs = [
        "LLVMGen/LLVMGen.cpp",
    ],
    deps = [
        "//include:BIR",
        "//include:LLVMGen",
        "//lib:BIR",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:BuiltinToLLVMIRTranslation",
        "@llvm-project//mlir:LLVMDialect",
        "@llvm-project//mlir:LLVMToLLVMIRTranslation",
        "@llvm-project//llvm:AllTargetsAsmParsers",
        "@llvm-project//llvm:AllTargetsCodeGens",
        "@llvm-project//llvm:Instrumentation",
    ],
)

# ------------------------------------------------------------------------------
# Diag
# ------------------------------------------------------------------------------

rust_static_library(
    name = "Diag-rs",
    crate_name = "belalang_diag",
    srcs = ["Diag/diag.rs"],
    deps = [
        "@crates//:annotate-snippets",
    ],
)

cc_library(
    name = "Diag",
    srcs = ["Diag/Diag.cpp"],
    deps = [
        "//include:Diag",
        ":Diag-rs",
    ],
)
