[package]
name = "belc_ast"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
belc_lexer.workspace = true
thiserror.workspace = true
