[package]
name = "belalang_web"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
belalang_core = { path = "../belalang_core" }
belalang_eval = { path = "../belalang_eval" }
wasm-bindgen = "0.2.92"
