load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "brt",
    srcs = glob(["src/**/*.c", "src/**/*.h"]),
    linkstatic = True,
    deps = [
        "@bdwgc//:bdwgc",
    ],
)

genrule(
    name = "bdwgc",
    srcs = ["@bdwgc//:bdwgc"],
    outs = ["libbdwgc.a"],
    cmd = "cp $(location @bdwgc//:bdwgc) $(RULEDIR)/libbdwgc.a",
    visibility = ["//visibility:public"],
)

genrule(
    name = "llvm_stackmaps_ld",
    srcs = ["src/llvm_stackmaps.ld"],
    outs = ["llvm_stackmaps.ld"],
    cmd = "cp $(location src/llvm_stackmaps.ld) $@",
    visibility = ["//visibility:public"],
)
