load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "brt",
    srcs = glob(
        ["src/**/*.c", "src/**/*.h"],
        exclude = ["src/**/*_test.*"],
    ),
)

cc_test(
    name = "gc_test",
    srcs = ["src/gc_test.cpp"],
    deps = [
        ":brt",
        "@googletest//:gtest_main",
    ],
)

genrule(
    name = "llvm_stackmaps_ld",
    srcs = ["src/llvm_stackmaps.ld"],
    outs = ["llvm_stackmaps.ld"],
    cmd = "cp $(location src/llvm_stackmaps.ld) $@",
    visibility = ["//visibility:public"],
)
