#!/usr/bin/env python3

# Generator for {out_file}

from urllib.request import urlopen
from contextlib import redirect_stdout

url = "https://www.unicode.org/Public/UCD/latest/ucd/DerivedCoreProperties.txt"
expected_first_line = "# DerivedCoreProperties-17.0.0.txt"
out_file = "include/belalang/Lexer/Unicode.h.inc"

def generate_for(lines, prop):
    print("#ifdef GEN_" + prop.upper())
    print("#undef GEN_" + prop.upper())

    target = f"; {prop}"

    for line in lines:
        if target not in line:
            continue
        h = line.split(";")[0].strip()

        if ".." in h:
            start, end = h.split("..")
        else:
            start = end = h

        print(f"{{ 0x{start}, 0x{end} }},")

    print("#endif // GEN_" + prop.upper())
    print()

def main():
    response = urlopen(url)
    lines = response.read().decode('utf-8').splitlines()

    # makes sure an update doesn't go unnoticed.
    assert lines[0] == expected_first_line, "newer version exists";

    with open(out_file, 'w') as f:
        with redirect_stdout(f):
            print("// Autogenerated by tools/generate-unicode.py")
            print("// Do NOT manually edit.\n")
            generate_for(lines, "XID_Start")
            generate_for(lines, "XID_Continue")

if __name__ == "__main__":
    main()
