name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use nightly toolchain
      run: rustup update nightly && rustup default nightly

    - name: Install nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: Run tests with nextest
      run: cargo nextest run --all --all-features
