[package]
name = "belalang_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
belalang = { path = ".." }
web-sys = { version = "0.3.69", features = ["Document", "Element", "Node", "Window"] }
